name: 'Test Deploy Action'
description: 'Provide a description here'
author: 'Your name or organization here'

branding:
  icon: 'heart'
  color: 'red'

inputs:
  milliseconds:
    description: 'Your input description here'
    required: true
    default: '1000'

outputs:
  time:
    description: 'Your output description here'

runs:
  using: node20
  main: dist/index.js
